quarkus:
  swagger-ui:
    always-include: true
  config:
    log:
      values: true
  log:
    category: 
      "io.smallrye.config":
        level: info
      "io.github.fungrim":
        level: debug