name: Gradle Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle 8.9
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: "8.9"

    - name: Build
      run: ./gradlew build

    - name: Contanerize
      uses: docker/build-push-action@v6
      with:
          push: true
          file: src/main/docker/Dockerfile.jvm
          tags: |
            fungrim/webhook-vector-ingest:latest
            fungrim/webhook-vector-ingest:0.0.${{github.run_number}}

  dependencies:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Generate dependencies
      uses: gradle/actions/dependency-submission@v4
